[package]
name = "tic_tac-toe_rs"
version = "0.1.0"
authors = ["sascha"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
